name: Linux build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: python3
          - language: java
            config: -old
          - language: java
            config: -new
          - language: csharp
          - language: r
          - language: scala
    container: ghcr.io/lballabio/quantlib-swig-devenv:${{ matrix.language }}
    steps:
    - name: Set up git permissions
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: actions/checkout@v3
    - name: Build and check
      run: |
        ./.build/${{ matrix.language }}${{ matrix.config }}.build
